### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ahaym**
Reviving this since I'm finally settled into work.

- Use Data.Colour as the colour representation
- New workflow: `|>` and `$>` (basically `Control.Arrow.>>>` and `Control.Lens.&`) for writing in a quasi-tidyverse style
- More complete representation of glyphs based around `Data.Default`

You can see how it looks in `example.hs`

### CODE REVIEW

**Comment by ocramz** [comment]
Great to hear back from you @ahaym ! : ) So you'd like to use the DataHaskell branch as the base for the project ?

**Comment by ahaym** [comment]
I'm happy with using this branch as base; preferably I'd like maintainer status though

**Comment by ocramz** [comment]
@ahaym you're admin now, welcome home! :)

**Comment by ahaym** [comment]
Great, thanks!

**Comment by NickSeagull** [comment]
So people ultimately like `|>` and `$>`? I thought it was the opposite 😮

**Comment by NickSeagull** [comment]
I usually used `|>` as `&` because lots of functional languages have it, and just `>>>`  for function composition, what do you think?

**Comment by ahaym** [comment]
The reason I decided not to re-export those functions is that they are different lengths, as it would be extra effort to indent them. You can also use `&` and `.`, as the order of the renderers isn't too important, but I think the current way may be more familiar to those coming from R. If people don't like the extra operators, I'm fine with removing them, though.

**Comment by NickSeagull** [comment]
Look great to me, and actually, I think that `$>` makes more sense than `|>`, and `|>` more than `>>>`

The only downside is that maybe `$>` can get confused with `<$`?

**Comment by ahaym** [comment]
Ah, you're completely right about `$>`, I need to find an alternative for it

**Pull request merged**
